export const VIDEOS = {
  short_video_one: require('../assets/videos/Billionaire.bride.E1.mp4'),
  short_video_two: require('../assets/videos/Billionaire.bride.E2.mp4'),
  short_video_three: require('../assets/videos/Billionaire.bride.E3.mp4'),
  short_video_four: require('../assets/videos/Billionaire.bride.E4.mp4'),
  short_video_five: require('../assets/videos/Billionaire.bride.E5.mp4'),
  short_video_six: require('../assets/videos/Billionaire.bride.E6.mp4'),
  cross_video: require('../assets/videos/cross.mp4'),
  better_call_saul_video: require('../assets/videos/better_call_sual.mp4'),
  landman_video: require('../assets/videos/landman.mp4'),
  landman_video_two: require('../assets/videos/landman_two.mp4'),
  the_boys_video: require('../assets/videos/the_boys.mp4'),
  doctor_house_video: require('../assets/videos/house.mp4'),
  doctor_house_video_two: require('../assets/videos/house_two.mp4'),
  no_good_deed_video: require('../assets/videos/no_good_deed.mp4'),
  no_good_deed_video_two: require('../assets/videos/no_good_deed_two.mp4'),
  lost_video: require('../assets/videos/lost.mp4'),
  black_dove_video: require('../assets/videos/black_dove.mp4'),
  black_dove_video_two: require('../assets/videos/black_dove_two.mp4'),
  dexter_video: require('../assets/videos/dexter.mp4'),
};
